# Generated by Django 5.2.6 on 2026-04-15 06:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrepSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prep_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('company_name', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('CLOSED', 'Closed')], default='ACTIVE', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prep_sessions', to='api.user')),
            ],
        ),
        migrations.CreateModel(
            name='PrepProfileSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('INTERVIEWEE', 'Interviewee'), ('INTERVIEWER', 'Interviewer')], max_length=20)),
                ('source', models.CharField(choices=[('LINKEDIN', 'LinkedIn')], default='LINKEDIN', max_length=20)),
                ('source_url', models.URLField(blank=True, max_length=500, null=True)),
                ('extracted_sections', models.JSONField(default=dict)),
                ('normalized_text', models.TextField(blank=True, default='')),
                ('confidence_flags', models.JSONField(default=dict)),
                ('metadata', models.JSONField(default=dict)),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_submissions', to='api.user')),
                ('prep_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_submissions', to='api.prepsession')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
    ]
