# Generated by Django 5.2.6 on 2026-04-21 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_enforce_unique_prep_session_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntervieweeBaselineProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('LINKEDIN', 'LinkedIn')], default='LINKEDIN', max_length=20)),
                ('source_url', models.URLField(blank=True, max_length=500, null=True)),
                ('extracted_sections', models.JSONField(default=dict)),
                ('normalized_text', models.TextField(blank=True, default='')),
                ('confidence_flags', models.JSONField(default=dict)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='interviewee_baseline_profile', to='api.user')),
            ],
        ),
    ]
