# Generated by Django 5.2.6 on 2026-05-11 12:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_intervieweebaselineprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewprediction',
            name='prep_session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='predictions', to='api.prepsession'),
        ),
    ]
